/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-29 06:27:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1728526346637L));
    _jspx_dependants.put("jar:file:/D:/springmvcstudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring_mvc01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Index</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>First Spring MVC</h1>\r\n");
      out.write("	<h1>Non-Annotation</h1>\r\n");
      out.write("	<h2><a href=\"/start1\">start1</a></h2>\r\n");
      out.write("	<h2><a href=\"/start2\">start2</a></h2>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<h1>Annotation</h1>\r\n");
      out.write("	<h2><a href=\"/start3\">start3</a></h2>\r\n");
      out.write("	<form action=\"/start4\" method=\"post\">\r\n");
      out.write("		<button type=\"submit\">start4-전송1</button>\r\n");
      out.write("		<input type=\"submit\" value=\"start4-전송2\">\r\n");
      out.write("	</form>\r\n");
      out.write("	<h2><a href=\"/start5\">start5</a></h2>\r\n");
      out.write("	<h2><a href=\"/start6\">start6</a></h2>\r\n");
      out.write("	<h2><a href=\"/start7\">start7</a></h2>\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	<h2>서버에게 정보 보내기</h2>\r\n");
      out.write("    <form action=\"/start8\" method=\"get\" autocomplete=\"on\">\r\n");
      out.write("        <p>\r\n");
      out.write("           <label> 이름 : <input type=\"text\" name=\"username\" placeholder=\"이름 입력\" required> </label></p>\r\n");
      out.write("        <p>   \r\n");
      out.write("           <label> 나이 : <input type=\"number\" name=\"userage\" placeholder=\"나이 입력\" required> </label>\r\n");
      out.write("        </p>\r\n");
      out.write("        <input type=\"submit\" value=\"서버에게 보내기\">\r\n");
      out.write("        <input type=\"reset\" value=\"취소\">\r\n");
      out.write("    </form>\r\n");
      out.write("    <br>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <form action=\"/calc\" method=\"post\">\r\n");
      out.write("    	<p> 수1 : <input type=\"number\" size=\"15\" name=\"s1\" required>\r\n");
      out.write("    	<p> 수2 : <input type=\"number\" size=\"15\" name=\"s2\" required>\r\n");
      out.write("    	<p> 연산자 :\r\n");
      out.write("    		<input type=\"radio\" name=\"op\" value=\"+\" checked>+\r\n");
      out.write("    		<input type=\"radio\" name=\"op\" value=\"-\">-\r\n");
      out.write("    		<input type=\"radio\" name=\"op\" value=\"*\">*\r\n");
      out.write("    		<input type=\"radio\" name=\"op\" value=\"/\">/\r\n");
      out.write("    	</p>\r\n");
      out.write("    	<p> 취미 : \r\n");
      out.write("    		<input type=\"checkbox\" name=\"hobby\" value=\"축구\"> 축구\r\n");
      out.write("    		<input type=\"checkbox\" name=\"hobby\" value=\"야구\"> 야구\r\n");
      out.write("    		<input type=\"checkbox\" name=\"hobby\" value=\"농구\"> 농구\r\n");
      out.write("    		<input type=\"checkbox\" name=\"hobby\" value=\"배구\"> 배구\r\n");
      out.write("    	</p>\r\n");
      out.write("    	\r\n");
      out.write("    	<input type=\"hidden\" name=\"cPage\" value=\"2\">\r\n");
      out.write("    	<input type=\"submit\" value=\"보내기\">\r\n");
      out.write("    </form> \r\n");
      out.write("    \r\n");
      out.write("    <br>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <form action=\"/calc2\" method=\"post\">\r\n");
      out.write("    	<p> 수1 : <input type=\"number\" size=\"15\" name=\"s1\" required>\r\n");
      out.write("    	<p> 수2 : <input type=\"number\" size=\"15\" name=\"s2\" required>\r\n");
      out.write("    	<p> 연산자 :\r\n");
      out.write("    		<input type=\"radio\" name=\"op\" value=\"+\" checked>+\r\n");
      out.write("    		<input type=\"radio\" name=\"op\" value=\"-\">-\r\n");
      out.write("    		<input type=\"radio\" name=\"op\" value=\"*\">*\r\n");
      out.write("    		<input type=\"radio\" name=\"op\" value=\"/\">/\r\n");
      out.write("    	</p>\r\n");
      out.write("    	<p> 취미 : \r\n");
      out.write("    		<input type=\"checkbox\" name=\"hobby\" value=\"축구\"> 축구\r\n");
      out.write("    		<input type=\"checkbox\" name=\"hobby\" value=\"야구\"> 야구\r\n");
      out.write("    		<input type=\"checkbox\" name=\"hobby\" value=\"농구\"> 농구\r\n");
      out.write("    		<input type=\"checkbox\" name=\"hobby\" value=\"배구\"> 배구\r\n");
      out.write("    	</p>\r\n");
      out.write("    	\r\n");
      out.write("    	<input type=\"hidden\" name=\"cPage\" value=\"2\">\r\n");
      out.write("    	<input type=\"submit\" value=\"보내기\">\r\n");
      out.write("    </form> \r\n");
      out.write("    <hr>\r\n");
      out.write("    <h3><a href=\"/member_list\">Members 전체 보기</a></h3>\r\n");
      out.write("    <hr>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 이미지는 무조건 webapp-resources 안에 넣어야 한다 -->\r\n");
      out.write("    <h3>이미지 보기</h3>\r\n");
      out.write("    <!-- img 보는 4가지 방법 -->\r\n");
      out.write("    <img alt=\"img01\" src=\"/resources/images/img01.jpg\" style=\"width: 100px;\"><br>\r\n");
      out.write("    <img alt=\"img01\" src=\"resources/images/img01.jpg\" style=\"width: 100px;\"><br>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <img alt=\"img01\" src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" style=\"width: 100px;\"><br>\r\n");
      out.write("    <img alt=\"img01\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" style=\"width: 100px;\"><br>\r\n");
      out.write("    <hr>\r\n");
      out.write("    \r\n");
      out.write("    <!-- cos 라이브러리 받아서 사용 -->\r\n");
      out.write("    <h3>파일 업로드-1</h3>\r\n");
      out.write("    <form action=\"/f_up1\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("    	<p>올린 사람 : <input type=\"text\" name=\"name\"></p>\r\n");
      out.write("    	<p>파일 : <input type=\"file\" name=\"f_name\"></p>\r\n");
      out.write("    	<p><input type=\"submit\" value=\"파일 업로드\"></p>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    <!-- commons-fileupload, commons-io 라이브러리 pom.xml에 등록\r\n");
      out.write("    	 servlet-context.xml 에서 파일 업로드용 클래스 등록\r\n");
      out.write("     -->\r\n");
      out.write("    <h3>파일 업로드-2</h3>\r\n");
      out.write("    <form action=\"/f_up2\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("    	<p>올린 사람 : <input type=\"text\" name=\"name\"></p>\r\n");
      out.write("    	<p>파일 : <input type=\"file\" name=\"f_name\"></p>\r\n");
      out.write("    	<p><input type=\"submit\" value=\"파일 업로드\"></p>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    <h3>파일 업로드-3</h3>\r\n");
      out.write("    <form action=\"/f_up3\" method=\"get\" enctype=\"multipart/form-data\">\r\n");
      out.write("    	<p>올린 사람 : <input type=\"text\" name=\"name\"></p>\r\n");
      out.write("    	<p>파일 : <input type=\"file\" name=\"f_name\"></p>\r\n");
      out.write("    	<p><input type=\"submit\" value=\"파일 업로드(get 에러날 예정)\"></p>\r\n");
      out.write("    </form>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <!-- VO를 이용해서 파라미터 처리 -->\r\n");
      out.write("    <h3>파일 업로드-4</h3>\r\n");
      out.write("    <form action=\"/f_up4\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("    	<p>올린 사람 : <input type=\"text\" name=\"name\"></p>\r\n");
      out.write("    	<p>파일 : <input type=\"file\" name=\"f_name\"></p>\r\n");
      out.write("    	<p><input type=\"submit\" value=\"파일 업로드\"></p>\r\n");
      out.write("    </form>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <h2><a href=\"/go_ajax_xml\">Ajax xml 연습하는 장소이동</a></h2>\r\n");
      out.write("    <h2><a href=\"/go_ajax_json\">Ajax json 연습하는 장소이동</a></h2>\r\n");
      out.write("    <h2><a href=\"/go_ajax_DB\">Ajax DB 연습하는 장소이동</a></h2>\r\n");
      out.write("    <h2><a href=\"/emp\">동적 쿼리 연습하는 장소이동</a></h2>\r\n");
      out.write("    <h2><a href=\"/email\">이메일 연습하는 장소이동</a></h2>\r\n");
      out.write("    <h2><a href=\"/login_form\">로그인 연습하는 장소이동</a></h2>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/index.jsp(10,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginchk == '1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("	alert(\"로그인 성공!\");\r\n");
        out.write("	");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/index.jsp(97,26) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/resources/images/img01.jpg");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/views/index.jsp(98,26) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("resources/images/img01.jpg");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager());
    return false;
  }
}
